# fly.toml app configuration file generated for supercharging-node-js-applications-with-sequelize-project on 2023-11-17T18:01:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "supercharging-node-js-applications-with-sequelize-project"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
