# fly.toml app configuration file generated for fly-mysql2 on 2023-11-17T17:05:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-mysql2"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "avalon_airlines"
  MYSQL_USER = "avalon_airlines"

[build]
  image = "mysql:5.7"

[experimental]
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql"
  ]
